# This file defines the main Snakefile for the workflow
# it includes configuration and workflow Snakefiles
# the targets are defined in the rule all below.

# include config file
# configfile: "config/config.yaml"

# include workflow files
include: "workflow/Snakefile"

# define rule all
rule all:
    input:
        "figures/shoebox_room_receiver_3_2.5_1.5.rt30.png",
        # "figures/shoebox_room_receiver_2_2.5_1.5.rt30.png",
        # "figures/shoebox_room_receiver_4_2.5_1.5.rt30.png",
